### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Pimentoso** [Paxa/fast_excel#57]
Hi, I was wondering if a new release is planned, since stuff like FastExcel::URL is mentioned in the documentation but it's not present in the 0.2.6 release.

**Comment by adamaiken89** [comment]
+ 1

**Comment by joshuapinter** [comment]
I agree with this. Of course, we can just use `master` in our `Gemfile` but a new release to show that it is maintained would be great. 

This is a great library that we've benchmarked against `writexlsx` and `xlsxstream`, and this was faaaaar quick, nearly 6x for larger files (6 hours instead of 32 hours) so I'd like to see this library get the attention it deserves. You've done a great job.

**Comment by adamFoldvari** [comment]
I would really appreciate a new release, since we have build problems with 0.2.6 (tha same as here: https://github.com/Paxa/fast_excel/issues/47). Using master solves the problem, but my team doesn't trust enough using master branch :D
Is there any plan on releasing 0.3.0?

**Comment by Paxa** [comment]
Released 0.3.0, sorry for delay
