### ISSUE TITLE
[qiestopm] benchmark against caxlsx

### ISSUE THREAD

**Issue by MadBomber** [Paxa/fast_excel#76]
The README file has an impress 4x speed bump pver axlsx.  I switched last year to spreadsheet_architect which is a wrapper for caxlsx.  What does your benchmarks show against caxlsx?

I'm asking because I have some files that are taking over 30 minutes to render with 5 sheets and less than 100K total rows.   fast_excel looks like a potential drop in replacement.

Dewayne
  o-*

**Comment by Paxa** [comment]
I didn't make benchmark to compare with caxlsx (PR is welcome). From my experience to generate half million rows (~20 columns) take 2 minutes or about 3-4k rows per second

It's important to measure data collection time and excel generation separately, because querying database make take more time than saving it to file. You may run your code with collecting data only (call `each do; end`) and compare with excel generating time

**Comment by Paxa** [comment]
Also if process consume too much memory, it will start using swap and it will reduce performance dramatically. To check memory usage I have gem https://github.com/paxa/process_memory

**Comment by MadBomber** [comment]
I've played with you examples under both Ruby 3.0.1 and 2.6.6 sufficiently to see that "fast" in an understatement.  I do some more detailed tests for the next month as time becomes available.

Your gem and its underlying library are impressive.  Thank you for your efforts.
